# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Fab Lab Limerick
description: A space for makers in Limerick city. Coming this April!
author:
  name: Colaborativa.eu
  email: info@colaborativa.eu

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: maruku
#   use_tex:    false
#   use_divs:   false
#   png_engine: blahtex
#   png_dir:    images/latex
#   png_url:    /images/latex

pygments: true
relative_permalinks: false

external:
  facebook: https://www.facebook.com/fablablimerick
  twitter: https://twitter.com/fablablimerick
  email: fablab(which is 'at' the)saul.ie
  wiki: https://github.com/FabLabLimerick/fablablimerick.github.io/wiki
  blog: http://fablablimerick.tumblr.com/
  map: "http://www.openstreetmap.org/?mlat=52.66593&mlon=-8.62399#map=18/52.66593/-8.62399"

# Prose configuration
prose:
  rooturl: "app/_posts/events"
  media: "img/events"
  metadata:
    _posts:
      events:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          help: "Introduce a title for the event"
      - name: "layout"
        field:
          element: "hidden"
          value: "single-event"
      - name: "category"
        field:
          element: "hidden"
          value: "events"      
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: "false"
          help: "Select false when writting a draft-event"
      - name: "slug"
        field:
          element: "text"
          label: "File Name or Slug"
           value: "thenewways-gregsaul"
		  help: "Introduce the event file name. Lowercase words without accent separated by dash (for example: 'thenewways-gregsaul')"   
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: "/events/thenewways-gregsaul/"
          help: "Introduce the relative link to the event based on the selected file name (for example: /events/thenewways-gregsaul/)
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
   		  help: "A short sentence introducing the event"
      - name: "hours"
        field:
          element: "text"
          label: "Hours"
		  help: "Date and time of the event celebration in humman readeable format (for example: 25th of March 6pm)
      - name: "description"
        field:
          element: "text"
          label: "Description"
          help: "A short paragraph describing the event"
      - name: "fee"
        field:
          element: "text"
          label: "Event Fee"
		  help: "Introduce the event fee (for example: 'Free event' or '€100 per person')	          
      - name: "soon"
        field:
          element: "checkbox"
          label: "More info link"
          value: "false"
		  help: "Enable or disable link to more info page"	          
      - name: "past"
        field:
          element: "checkbox"
          label: "Past Event"
          value: "false"
		  help: "Select true or false to indicate that it is a past or future event"       
      - name: "image"
        - name: "url"
          field:
            element: "text"
            label: "Relative link to an image"
            value: "/events/thenewways-gregsaul.jpg"
		    help: "Please load and name the image accordingly"
		- name: "caption"
		  - name: "display"
            field:
              element: "checkbox"
              label: "Show image caption"
              value: "false"
		      help: "Select true or false to show or hide the image caption"
		  - name: "title"
            field:
              element: "text"
              label: "Image caption"
		      help: "Introduce the image caption"
		  - name: "credits"
            field:
              element: "text"
              label: "Image credits"
		      help: "Introduce the image credits"	
		  - name: "original"
            field:
              element: "text"
              label: "External Link"
		      help: "Introduce the external link to the original credited image"			    	      	          


