# Prose configuration
prose:
  ignore:
    - *.html
    - *.md
    - *.txt
    - *.jpg
    - *.png
    - *.ico
    - *.xml
    - CNAME
    - .htaccess
    - /js
    - /_bower_components
    - /banner-homepage
    - /banner-space
    - /css
    - /equipment
    - /fonts
    - /img
    - /press
    - /research
    - /space
    - /team
    - /team-category
    - /_layouts
    - /_includes
